name = "views-analytics-via-cf"
main = "src/index.ts"
compatibility_date = "2023-06-23"

kv_namespaces = [
  { binding = "ZZ_STORES_ANALYTICS", preview_id = "5d96a94d545a4db5a1ba37b9fbf2ba7d", id = "5d96a94d545a4db5a1ba37b9fbf2ba7d" }
]

[triggers]
crons = ["* * * * *"]

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "views_analytics"
database_id = "f49dfa98-342f-4206-aa9c-7a23fede9060"

[dev]
ip = "localhost"
port = 8787
local_protocol = "http"