name = "views-analytics-via-cf"
main = "src/index.ts"
compatibility_date = "2023-06-23"

kv_namespaces = [
  { binding = "kv", preview_id = "", id = "" }
]

[triggers]
crons = ["0 */2 * * *"] # run every 2 hours

[[ d1_databases ]]
binding = "database" # i.e. available in your Worker on env.DB
database_name = "views_analytics"
database_id = ""

[dev]
ip = "localhost"
port = 8787
local_protocol = "http"