name = "views-analytics-via-cf"
main = "src/index.ts"
compatibility_date = "2023-06-30"

kv_namespaces = [
  { binding = "ZZ_STORES_ANALYTICS", preview_id = "5d96a94d545a4db5a1ba37b9fbf2ba7d", id = "5d96a94d545a4db5a1ba37b9fbf2ba7d" }
]

[triggers]
crons = ["* * * * *"]

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "views-analytics-via-cf"
database_id = "4c81dc43-8827-4d4d-9d01-0c395af6fa9e"