name = "views-analytics-via-cf"
main = "src/index.ts"
compatibility_date = "2023-06-23"

kv_namespaces = [
  { binding = "ZZ_STORES_ANALYTICS", preview_id = "", id = "" }
]

[triggers]
crons = ["* * * * *"]

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "views_analytics"
database_id = ""

[dev]
ip = "localhost"
port = 8787
local_protocol = "http"