name = "analytics-core"
main = "src/index.ts"
compatibility_date = "2023-06-23"

kv_namespaces = [
  { binding = "kv", preview_id = "you-kv-id", id = "you-kv-id" },
]

[triggers]
crons = ["*/1 * * * *"] # run every 2 hours

[dev]
ip = "localhost"
port = 8787
local_protocol = "http"

[[d1_databases]]
binding = "database" # i.e. binding available in your Worker on env.DB 
database_name = "dayen-analytics"
database_id = "you-db-id"
