name = "analytics-core"
main = "src/index.ts"
compatibility_date = "2023-06-23"

[triggers]
crons = []

[dev]
ip = "localhost"
port = 8787
local_protocol = "http"

[[d1_databases]]
binding = "database" # i.e. binding available in your Worker on env.DB 
database_name = "dayen-analytics"
database_id = "your-db-id"
