name: Deploying Dayen Analytics apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy core app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: node version
        run: node -v
      - name: Current working directory
        run: pwd
      - name: Install dependencies
        run: cd ui/ && yarn --frozen-lockfile && yarn pages:build
      - name: Where we are? what in there?
        run: pwd && ls -laF ui/
      - name: Publish
        uses: cloudflare/wrangler-action@3.0.0
        with:
          apiKey: ${{ secrets.CF_API_KEY }}
          email: ${{ secrets.CF_EMAIL }}
          command: pages deploy ui/.vercel/output/static
      